import {
  GitHubIcon,
  LinkedInIcon,
  DiscordIcon,
  XIcon,
} from "@/components/icons"

export const RESUME_DATA = {
  name: "Nathan Roark",
  initials: "NR",
  location: "Huntsville, AL",
  locationLink: "https://www.google.com/maps/place/Huntsville",
  about:
    "Full Stack Engineer passionate about building and learning new things",
  summary:
    "As a Full Stack Engineer, I have successfully built many projects from start to finish for engineers internally and for customers. Currently, I work mostly with TypeScript, React, and Rust languages and have a Secret Security Clearance. I have over 3 years of experience in working professionally on various software teams.",
  avatarUrl: "it-me.png",
  personalWebsiteUrl: "https://nathanroark.dev",
  contact: {
    email: "nathanroark@protonmail.com",
    social: [
      {
        name: "GitHub",
        url: "https://github.com/NathanRoark",
        icon: GitHubIcon,
      },
      {
        name: "LinkedIn",
        url: "https://www.linkedin.com/in/nathan-roark/",
        icon: LinkedInIcon,
      },
      {
        name: "X",
        url: "https://x.com/nathanroark",
        icon: XIcon,
      },
      {
        name: "Discord",
        url: "https://discordapp.com/users/nroark",
        icon: DiscordIcon,
      },
    ],
  },
  education: [
    {
      school: "The University of Alabama in Huntsville",
      degree: "Master's Degree in Computer Science",
      year: "May 2025",
      extra: "4.0 GPA",
    },
    {
      school: "The University of Alabama in Huntsville",
      degree: "Bachelor's Degree in Computer Engineering",
      year: "Dec 2020",
      extra: "Dean's List",
    },
  ],
  work: [
    {
      company: "Trideum",
      link: "https://www.trideum.com/",
      badges: ["Remote"],
      title: "Full Stack Engineer",
      start: "March 2023",
      end: "Present",
      bullets: [
        "Led a team of 5 engineers to develop the frontend for an AI application designed for use in operational testing", // TCAI
        "Developed an application extension enabling real-time note-taking and sharing at scale during Cyber Table Top events and other similar scenarios.", // Notetaker
        "Built an application to visualize flight paths generated by an AI running on a microcontroller.", // Flight Viz
        "Created an application for visualizing and interacting with large, complex datasets in both 2D and 3D spaces.", // Data Viz
      ],
    },
    {
      company: "Trideum",
      link: "https://www.trideum.com/",
      badges: [],
      title: "Software Engineer",
      start: "March 2021",
      end: "March 2023",
      bullets: [
        "Developed an application capable of transforming various military and simulation message formats into other desired formats.", // Hermes
        "Built a new modeling and simulation application to interface with existing systems, processing Link16, VMF, and DIS traffic.", // BluPill
        "Updated and maintained several internal tools and external applications for customers.", // CT3, Radar Emulator, Eventman
      ],
    },
  ],
  skills: [
    "JavaScript",
    "TypeScript",
    "React",
    "Svelte",
    "Next.js",
    "Node.js",
    "Rust",
    "C++",
    "Qt",
    "D3",
    "Tailwind",
    "MongoDB",
    "Unity",
  ],
  projects: [
    {
      title: "Pong Wars",
      description: "Pong Wars using Canvas",
      techStack: ["Svelte", "SveltekKit", "TypeScript", "Tailwind"],
      link: {
        label: "pong-wars.nathanroark.dev",
        href: "https://pong-wars.nathanroark.dev",
      },
    },
    {
      title: "Coverflow",
      description: "Demo site for a beautiful coverflow.",
      techStack: ["NextJS", "TypeScript", "React", "SASS", "Styled Components"],
      link: {
        label: "coverflow.nathanroark.dev",
        href: "https://coverflow.nathanroark.dev",
      },
    },
    {
      title: "Life",
      description: "Conway's Game of Life",
      techStack: [
        "NextJS",
        "React",
        "immer",
        "Styled Components",
        "TypeScript",
        "Tailwind",
      ],
      link: {
        label: "life.nathanroark.dev",
        href: "https://life.nathanroark.dev",
      },
    },
    {
      title: "Data Viz Demos",
      description: "Demo site for some custom D3 Vizualizations.",
      techStack: ["NextJS", "TypeScript", "React", "D3", "Tailwind"],
      link: {
        label: "data-viz.nathanroark.dev",
        href: "https://data-viz.nathanroark.dev",
      },
    },
    {
      title: "Wolf Sheep Predation",
      description: "Wolf Sheep Predation Simulation using Agent Based Modeling",
      techStack: ["NextJS", "React", "TypeScript"],
      link: {
        label: "wolf-sheep-predation.nathanroark.dev",
        href: "https://wolf-sheep-predation.nathanroark.dev",
      },
    },
    {
      title: "Blog",
      description:
        "Static Blog for showing and talking about media that I like.",
      techStack: ["Astro", "TypeScript", "Tailwind", "Markdown"],
      link: {
        label: "nathanroark.com",
        href: "https://nathanroark.com",
      },
    },
    {
      title: "CV",
      description:
        "This website! My developer website to show my software engineering self.",
      techStack: ["NextJS", "TypeScript", "Tailwind"],
      link: {
        label: "nathanroark.dev",
        href: "https://nathanroark.dev",
      },
    },

    // {
    //   title: "Consultly",
    //   techStack: [
    //     "Side Project",
    //     "TypeScript",
    //     "Next.js",
    //     "Vite",
    //     "GraphQL",
    //     "WebRTC",
    //   ],
    //   description: "A platform to build and grow your online business",
    //   logo: ConsultlyLogo,
    //   link: {
    //     label: "consultly.com",
    //     href: "https://consultly.com/",
    //   },
    // },
    // {
    //   title: "Monito",
    //   techStack: ["Side Project", "TypeScript", "Next.js", "Browser Extension"],
    //   description:
    //     "Browser extension that records everything happening in a web application",
    //   logo: MonitoLogo,
    //   link: {
    //     label: "monito.dev",
    //     href: "https://monito.dev/",
    //   },
    // },
    // {
    //   title: "Jarocki.me",
    //   techStack: ["Side Project", "Next.js", "MDX"],
    //   description:
    //     "My personal website and blog. Built with Next.js and Notion API",
    //   logo: JarockiMeLogo,
    //   link: {
    //     label: "github.com",
    //     href: "https://jarocki.me/",
    //   },
    // },
    // {
    //   title: "Minimal",
    //   techStack: ["Side Project", "Next.js", "Puppeteer"],
    //   description:
    //     "Minimalist calendars, habit trackers and planners generator",
    //   logo: Minimal,
    //   link: {
    //     label: "useminimal.com",
    //     href: "https://useminimal.com/",
    //   },
    // },
    // {
    //   title: "Barepapers",
    //   techStack: ["Side Project", "Next.js", "Puppeteer"],
    //   description:
    //     "Generates beautiful wallpapers using random shapes and gradients",
    //   logo: BarepapersLogo,
    //   link: {
    //     label: "barepapers.com",
    //     href: "https://barepapers.com/",
    //   },
    // },
    // {
    //   title: "Year progress",
    //   techStack: ["Side Project", "TypeScript", "Next.js"],
    //   description: "Tracks current year progress and displays a countdown",
    //   logo: YearProgressLogo,
    //   link: {
    //     label: "getyearprogress.com",
    //     href: "https://getyearprogress.com/",
    //   },
    // },
    // {
    //   title: "Parabol",
    //   techStack: [
    //     "Full Stack Developer",
    //     "TypeScript",
    //     "React",
    //     "Node.js",
    //     "GraphQL",
    //   ],
    //   description:
    //     "The Agile meeting co-pilot that delivers better meetings with less effort",
    //   logo: ParabolLogo,
    //   link: {
    //     label: "github.com",
    //     href: "https://parabol.co/",
    //   },
    // },
    // {
    //   title: "Evercast",
    //   techStack: [
    //     "Lead Frontend Developer",
    //     "TypeScript",
    //     "React",
    //     "Node.js",
    //     "GraphQL",
    //   ],
    //   description:
    //     "Creative collaboration platform that combines video conferencing and HD media streaming",
    //   logo: EvercastLogo,
    //   link: {
    //     label: "evercast.us",
    //     href: "https://www.evercast.us/",
    //   },
    // },
    // {
    //   title: "Mobile Vikings",
    //   techStack: ["Lead Android Developer", "Android", "Kotlin"],
    //   description:
    //     "Android application for leading virtual mobile operator in Poland",
    //   logo: MobileVikingsLogo,
    //   link: {
    //     label: "mobilevikings.pl",
    //     href: "https://mobilevikings.pl/",
    //   },
    // },
    // {
    //   title: "Howdy",
    //   techStack: ["Lead Android Developer", "Android", "Kotlin"],
    //   description:
    //     "Howdy is a place for you to join communities you care about",
    //   logo: Howdy,
    //   link: {
    //     label: "play.google.com",
    //     href: "https://howdy.co/",
    //   },
    // },
    // {
    //   title: "Tastycloud",
    //   techStack: ["Lead Android Developer", "Android", "Kotlin"],
    //   description:
    //     "Android application for managing and displaying restaurant menus in kiosk mode",
    //   logo: TastyCloudLogo,
    //   link: {
    //     label: "tastycloud.fr",
    //     href: "https://www.tastycloud.fr/",
    //   },
    // },
    // {
    //   title: "Ambit",
    //   techStack: ["Lead Android Developer", "Android", "Kotlin"],
    //   description:
    //     "Android application that helps with sharing your contact details",
    //   logo: AmbitLogo,
    // },
    // {
    //   title: "Bim",
    //   techStack: ["Lead Android Developer", "Android", "Kotlin"],
    //   description:
    //     "Android application that helps with booking a table in a restaurants",
    //   logo: BimLogo,
    // },
    // {
    //   title: "Canal Digital GO",
    //   techStack: ["Lead Android Developer", "Android", "Kotlin"],
    //   description:
    //     "Video streaming mobile application for Canal Digital subscribers",
    //   logo: CDGOLogo,
    // },
  ],
} as const
